SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK_SALES bs
JOIN BOOK b ON bs.BOOK_ID = b.BOOK_ID
JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE bs.SALES_DATE LIKE "2022-01%"
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC;